#plugin information
id: Amazon
name: Amazon
version: 0.03

#about this plugin
description: <__trans phrase="Function set for Amazon API">
author_name: <__trans phrase="ToI Inc.">
author_link: http://tec.toi-planning.net/
plugin_link: http://tec.toi-planning.net/mt/amazon/
doc_link: http://tec.toi-planning.net/mt/amazon/manual

#Localization
l10n_class: MT::Amazon::L10N

init_app: $Amazon::MT::Amazon::init_app

settings:
    amazon_s3_access_key:
    amazon_s3_secret_key:
    amazon_s3_bucket:
    amazon_s3_distribution_domain_names:
    amazon_s3_suffixes:
    amazon_s3_for_all_template:

blog_config_template: amazon_blog_config.tmpl

schema_version: 8
object_types:
    template:
        amazon_s3_enabled:
            type: boolean
            default: 0
            not_null: 0

tags:
    help_url: http://tec.toi-planning.net/mt/amazon/tags#%t
    function:
        Link: $Amazon::MT::Amazon::S3::_hdlr_link

callbacks:
    build_file: $Amazon::MT::Amazon::S3::build_file
    MT::Template::pre_save: $Amazon::MT::Amazon::S3::template_pre_save
    MT::App::CMS::template_param.edit_template: $Amazon::MT::Amazon::S3::param_edit_template
